---
language: node_js
node_js:
  - "5.10.1"

sudo: false

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  code_climate:
    repo_token: 0e4875fa652edb14844274a0ccc89a7fe327e8a05ab241c3f53e196f8c79eb87

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO --skip-cleanup=true --- ember test

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.dat
